name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JDK environment
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Access Secrets
        env:
          TMDB_API_KEYS: ${{ secrets.TMDB_API_KEYS }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          SUBDL_API_KEY: ${{ secrets.SUBDL_API_KEY }}
          RABBITSTREAM_SOURCE_API: ${{ secrets.RABBITSTREAM_SOURCE_API }}
        run: |
          echo TMDB_API_KEYS=$TMDB_API_KEYS >> local.properties
          echo TMDB_API_KEY=$TMDB_API_KEY >> local.properties
          echo SUBDL_API_KEY=$SUBDL_API_KEY >> local.properties
          echo RABBITSTREAM_SOURCE_API=$RABBITSTREAM_SOURCE_API >> local.properties

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Create Release
        id: create_release
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const tag = process.env.GITHUB_REF_NAME ||
              context.ref.replace(/^refs\/tags\//, '');
            let release;

            try {
              release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag,
              });
            } catch (error) {
              if (error.status !== 404) throw error;

              release = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag,
                name: `Release ${tag}`,
              });
            }

            core.info(`Using release ${release.data.html_url}`);

      - name: Upload Release APK
        env:
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: ${{ steps.sign_apk.outputs.signedReleaseFile }}
          ASSET_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}.apk
        run: gh release upload "${{ github.ref_name }}" "$ASSET_PATH#$ASSET_NAME" --clobber


      - name: Set Mobile version
        run: |
          echo APP_LAYOUT=mobile >> local.properties

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        id: sign_apk_mobile
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Release APK
        env:
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: ${{ steps.sign_apk_mobile.outputs.signedReleaseFile }}
          ASSET_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}-only-mobile.apk
        run: gh release upload "${{ github.ref_name }}" "$ASSET_PATH#$ASSET_NAME" --clobber


      - name: Set TV version
        run: |
          echo APP_LAYOUT=tv >> local.properties

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        id: sign_apk_tv
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Release APK
        env:
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: ${{ steps.sign_apk_tv.outputs.signedReleaseFile }}
          ASSET_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}-only-tv.apk
        run: gh release upload "${{ github.ref_name }}" "$ASSET_PATH#$ASSET_NAME" --clobber
